// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    var $button, $el, $urlEl, el, lc,
      _this = this;
    lc = $('.literally').literallycanvas({
      backgroundColor: 'whiteSmoke',
      imgurKey: '9600756ae5f127ca192d991140ee28c4'
    });
    el = $('.share-to-imgur').get(0);
    $el = $(el);
    $button = $el.find('button');
    $urlEl = $el.find('.imgur-url');
    $button.click(function(e) {
      $urlEl.html('Uploading...');
      $button.attr('disabled', 'disabled');
      return lc.uploadCanvasToImgur().done(function(url) {
        return $el.find('.imgur-url').html($('<a href="' + url + '">' + url + '</a>'));
      }).fail(function(msg) {
        return $urlEl.html(_.escape(msg));
      }).always(function() {
        return $button.removeAttr('disabled');
      });
    });
    $('.get-image').click(function(e) {
      return window.open($('.literally').canvasForExport().toDataURL());
    });
    $('.literally').resizable();
    return console.log(1);
  });

}).call(this);
